project:
  type: website

website:
  title: "Matt's IS415 Experience"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu:
        - text: "Hands-on Exercise 1"
          href: HandsOnEx/HE1/HE1.qmd
        - text: "Hands-on Exercise 2"
          href: HandsOnEx/HE2/HE2.qmd
        - text: "Hands-on Exercise 3"
    - text: "Take-home Exercises"
      menu:
        - text: "Take-home Exercise 1"
        - text: "Take-home Exercise 2"
        - text: "Take-home Exercise 3"
    - text: "In-class Exercises"
      menu:
        - text: "In-class Exercises 1"
          href: InClassEx/ICE1/ICE1.qmd
        - text: "In-class Exercises 2"
          href: InclassEx/ICE2/ICE2.qmd
        - text: "In-class Exercises 3"
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

