project:
  type: website

website:
  title: "Matt's IS415 Experience"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu:
        - text: "Hands-on Exercise 1"
          href: HandsOnEx/HE1/HE1.html
        - text: "Hands-on Exercise 2"
          href: HandsOnEx/HE2/HE2.html
        - text: "Hands-on Exercise 3"
          href: HandsOnEx/HE3/HE3.html
        - text: "Hands-on Exercise 4"
          href: HandsOnEx/HE4/HE4.html
        - text: "Hands-on Exercise 5 & 6"
          href: HandsOnEx/HE5/HE5.html
        - text: "Hands-on Exercise 7"
          href: HandsOnEx/HE7/HE7.html
        - text: "Hands-on Exercise 8"
          href: HandsOnEx/HE8/HE8.html
        - text: "Hands-on Exercise 9"
          href: HandsOnEx/HE9/HE9.html
        - text: "Hands-on Exercise 10"
          href: HandsOnEx/HE10/HE10.html
        - text: "Hands-on Exercise 11"
          href: HandsOnEx/HE11/HE11.html          
    - text: "Take-home Exercises"
      menu:
        - text: "Take-home Exercise 1"
          href: TakeHomeEx/TakeHomeEx1/THE1.html
        - text: "Take-home Exercise 2"
          href: TakeHomeEx/TakeHomeEx2/THE2.html
        - text: "Take-home Exercise 3"
          href: TakeHomeEx/TakeHomeEx3/THE3.html
    - text: "In-class Exercises"
      menu:
        - text: "In-class Exercises 2"
          href: InclassEx/ICE2/ICE2.html
        - text: "In-class Exercises 3"
          href: InClassEx/ICE3/ICE3.html
        - text: "In-class Exercises 3.1"
          href: InClassEx/ICE3/ICE3_1.html
        - text: "In-class Exercises 4"
          href: InClassEx/ICE4/ICE4.html
        - text: "In-class Exercises 5"
          href: InClassEx/ICE5/ICE5.html
        - text: "In-class Exercises 7"
          href: InClassEx/ICE7/ICE7.html
        - text: "In-class Exercises 8"
          href: InClassEx/ICE8/ICE8.html
        - text: "In-class Exercises 9"
          href: InClassEx/ICE9/ICE9.html
        - text: "In-class Exercises 10"
          href: InClassEx/ICE10/ICE10.html
        - text: "In-class Exercises 11"
          href: InClassEx/ICE11/ICE11.html
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: 
     - united
     - custom.scss
    toc: true

editor: visual

