project:
  type: website

website:
  title: "IS415"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu:
        - text: "Hands-on Exercise 1"
          href: HandsOnEx/HE1/HE1.qmd
        - text: "Hands-on Exercise 2"
        - text: "Hands-on Exercise 3"
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

