---
title: "Take-Home Exercise 1"
author:
  - name: Matthew Ho
    url: https://www.linkedin.com/in/matthewhoyiwen/
date: 02-11-2024
description: |
  Take-Home Exercise 2
categories:
  - Take-Home Exercise
format:
  html:
    toc: true
execute: 
  eval: true
  echo: true
  warning: false
---

## 1.0 Overview

## 2.0 Wrangling

```{r}
pacman::p_load(sf, spdep, tmap, tidyverse, ggplot2, smoothr, lubridate, sfdep)
```

```{r}
twv <- st_read(dsn = "data/geospatial", 
                 layer = "TAINAN_VILLAGE")
```

```{r}
dengued <- read_csv("data/aspatial/Dengue_Daily.csv")
```

```{r}
dengued <- dengued[, c(1, 10, 11)]
names(dengued)
```

```{r}
names(dengued) <- c("Onset", "X", "Y")
names(dengued)
```

```{r}
head(dengued)
```

```{r}
options(digits = 15)
```

```{r}
dengued[, c(2, 3)] <- lapply(dengued[, c(2, 3)], as.numeric)
head(dengued)
```

```{r}
sum(apply(dengued, 1, function(x) any(is.na(x))))
```

```{r}
dengued <- na.omit(dengued)
```

```{r}
sum(apply(dengued, 1, function(x) any(is.na(x))))
```

```{r}
hist(dengued$Onset, breaks = "days", xlab = "Date", ylab = "Frequency", main = "Histogram of Date Ranges")
```

```{r}
st_crs(twv)
```

```{r}
dengued_sf <- st_as_sf(dengued, coords = c("X", "Y"),
                      crs = 3824)
st_crs(dengued_sf)
```

```{r}
head(dengued_sf)
```

```{r}
twvsz <- twv[twv$TOWNID %in% c("D01", "D02", "D04", "D06", "D07", "D08", "D32", "D39"), ] %>% 
  subset(select = -NOTE)
```

```{r}
head(twvsz)
```

```{r}
plot(twvsz)
```

```{r}
u_twvsz <- st_union(twvsz)
plot(u_twvsz)
```

```{r}
unh_twvsz <- fill_holes(u_twvsz, units::set_units(1, "km^2"))
plot(unh_twvsz)
```

```{r}
diff_twvsz <- st_difference(unh_twvsz, u_twvsz)
plot(diff_twvsz)
```

```{r}
hole_victims <- st_intersection(dengued_sf, diff_twvsz)
head(hole_victims)
```

Epi weeks 31-50 2023: 30-07-23 to 16-12-23

```{r}
dengued_sf_epiweeks <- dengued_sf %>% filter(Onset >= as.Date("2023-07-30") & Onset <= as.Date("2023-12-16"))
```

```{r}
dengue_sf <- st_intersection(dengued_sf_epiweeks, u_twvsz)
```

```{r}
dengue_sf$epi_week <- epiweek(dengue_sf$Onset)
```


```{r}
write_rds(dengue_sf, "data/rds/dengue_sf.rds")
```

```{r}
tm_shape(u_twvsz) + 
  tm_polygons() +
tm_shape(dengue_sf) +
  tm_dots(col = "red")
```

```{r}
geo_dupes <- any(duplicated(dengue_sf$geometry))
geo_dupes
```

```{r}
vil_dupes <- any(duplicated(twvsz$VILLCODE))
vil_dupes
```

Keep the NA for geometry purposes
```{r}
dengue_vils_sf <- st_join(twvsz, dengue_sf)
```
```{r}
dengue_vils_sf[!rownames(dengue_vils_sf) %in% rownames(na.omit(dengue_vils_sf)), ]
```

```{r}
dengue_vils_sf <- dengue_vils_sf[!is.na(dengue_vils_sf$VILLCODE), ]
```

Account for the NA village
```{r}
dengue_vils_gb_vc <- dengue_vils_sf %>%
  group_by(VILLCODE, VILLENG) %>%
  summarise(count = sum(!is.na(epi_week)))
```
```{r}
dengue_vils_gb_vc_epi <- dengue_vils_sf %>%
  group_by(VILLCODE, epi_week) %>%
  summarise(count = sum(!is.na(epi_week)))
```

```{r}
plot(dengue_vils_gb_vc_epi)
```

```{r}
spt <- as_spacetime(dengue_vils_gb_vc_epi, "VILLCODE", "epiweek")
```

```{r}
activate(spt, "geometry")
```

```{r}
activate(spt, "data")
```

```{r}
write_rds(spt, "data/rds/spt.rds")
```

If data is full of landmines, the NA value remaining partially throughout the process was a dirty needle. It doesn't hurt much now, but it might mess me up in the long run.

## 3.0 EDA

```{r}
set.seed(42)
# tmap_options(check.and.fix = TRUE)
```

### 3.1 Global Spatial Autocorrelation

See 36 <=
```{r}
# plot(dengue_vils_gb_ew)
```

Inspired by 

https://jenpoer-is415-gaa-exercises.netlify.app/take-home-exercises/exe-02/the2#exploratory-data-analysis-eda-with-choropleth-maps
```{r}
choropleth_map_small_multiples <- function(df, varname, facet, colors) {
  tm_shape(df) +
    tm_polygons(col='white') +
  tm_shape(df) +
    tm_polygons(varname,
            palette = colors,
            style="quantile") +
    tm_facets(by=facet, free.coords = FALSE)
}
```

```{r}
choropleth_map_small_multiples(dengue_vils_gb_vc_epi, "count", "epi_week", "Blues")
```

```{r}
dv_total_wm_q <- poly2nb(dengue_vils_gb_vc, 
                queen=TRUE)

dv_total_rswm_q <- nb2listw(dv_total_wm_q, 
                   style="W", 
                   zero.policy = TRUE)

summary(dv_total_wm_q)
```

```{r}
moran.test(dengue_vils_gb_vc$count,
           listw=dv_total_rswm_q,
           zero.policy = TRUE,
           na.action=na.omit)
```
```{r}
moran_mc_res = moran.mc(dengue_vils_gb_vc$count,
                listw=dv_total_rswm_q, 
                nsim=999, 
                zero.policy = TRUE, 
                na.action=na.omit)
moran_mc_res
```

```{r}
summary(moran_mc_res$res[1:999])
```

```{r}
var(moran_mc_res$res[1:999])
```
```{r}
ggplot() + 
  aes(moran_mc_res$res[1:999]) + 
  geom_histogram(colour="black", fill="pink") + 
  labs(title = "Histogram of Simulated Moran's I For Tainan City Dengue Cases",
       x = "Simulated Moran's I",
       y = "Occurences") +
  theme_minimal()
```

```{r}
MI_corr <- sp.correlogram(dv_total_wm_q, 
                          dengue_vils_gb_vc$count, 
                          order=8, 
                          method="I", 
                          style="W")
plot(MI_corr)
print(MI_corr)
```
### Local

```{r}
fips <- order(dengue_vils_gb_vc$VILLCODE)
localMI <- localmoran(dengue_vils_gb_vc$count, dv_total_rswm_q)
head(localMI)
```

```{r}
dengue_vils_gb_vc.localMI <- cbind(dengue_vils_gb_vc,localMI) %>%
  rename(Pr.Ii = Pr.z....E.Ii..)
```

```{r}
p_val_2_cats <- function(x) {
  if (x <= 0.005) {
    return("p <= 0.005")
  } else if (x <= 0.01) {
    return("p <= 0.01")
  } else if (x <= 0.05) {
    return("p <= 0.05")
  } else {
    return("p > 0.05")
  }
}

dengue_vils_gb_vc.localMI <- dengue_vils_gb_vc.localMI %>%
  mutate(p_values = sapply(Pr.Ii, p_val_2_cats))
```

```{r}
tm_shape(dengue_vils_gb_vc.localMI) +
  tm_fill(col = "Ii", 
          style = "pretty",
          palette = "RdBu",
          title = "local moran statistics") +
  tm_borders(alpha = 0.5) + 
  
tm_shape(dengue_vils_gb_vc.localMI[dengue_vils_gb_vc.localMI$p_values != "p > 0.05", ]) +
  tm_symbols(col = "p_values",
             title.shape = "P Values:",
             shapes.labels = c("p <= 0.05", "p <= 0.01", "p <= 0.005"),
             size = 0.1,
             palette=c('purple', 'hotpink', 'white'))
```

```{r}
dengue_vils_gb_vc$count_Z <- scale(dengue_vils_gb_vc$count) %>% 
  as.vector 

moran.plot(dengue_vils_gb_vc$count_Z, dv_total_rswm_q,
                  labels=dengue_vils_gb_vc$VILLENG,
                  xlab="Dengue Cases Standardised",
                  ylab="Spatial Lag of Dengue Cases Standardised")
```

```{r}
quadrant <- vector(mode="numeric",length=nrow(localMI))
dengue_vils_gb_vc$lag_count <- lag.listw(dv_total_rswm_q, dengue_vils_gb_vc$count)
DV <- dengue_vils_gb_vc$count - mean(dengue_vils_gb_vc$count)     
LM_I <- localMI[,1]   
signif <- 0.05       
quadrant[DV <0 & LM_I>0] <- 1
quadrant[DV >0 & LM_I<0] <- 2
quadrant[DV <0 & LM_I<0] <- 3  
quadrant[DV >0 & LM_I>0] <- 4    
quadrant[localMI[,5]>signif] <- 0
```

```{r}
dengue_vils_gb_vc.localMI$quadrant <- quadrant

print(unique(dengue_vils_gb_vc.localMI$quadrant))

colors <- c("#ffffff", "#2c7bb6", "#abd9e9", "#fdae61", "#d7191c")
clusters <- c("insignificant", "low-low", "low-high", "high-low", "high-high")

tm_shape(dengue_vils_gb_vc.localMI) +
  tm_fill(col = "quadrant", 
          style = "cat", 
          palette = colors[c(sort(unique(quadrant)))+1], 
          labels = clusters[c(sort(unique(quadrant)))+1],
          popup.vars = c("")) +
  tm_borders(alpha=0.5)
```

```{r}
dengue_count <- qtm(dengue_vils_gb_vc, "count")

dengue_vils_gb_vc$quadrant <- quadrant
colors <- c("#ffffff", "#2c7bb6", "#abd9e9", "#fdae61", "#d7191c")
clusters <- c("insignificant", "low-low", "low-high", "high-low", "high-high")

LISAmap <- tm_shape(dengue_vils_gb_vc.localMI) +
  tm_fill(col = "quadrant", 
          style = "cat", 
          palette = colors[c(sort(unique(quadrant)))+1], 
          labels = clusters[c(sort(unique(quadrant)))+1],
          popup.vars = c("")) +

  tm_borders(alpha=0.5)

tmap_arrange(dengue_count, LISAmap, 
             asp=1, ncol=2)
```


### Hot and Cold






























































































































































































































































































































































